more consisten fonts and less redunancy in CSS
Sage-Bionetworks/web-mpower-2 pull request #8
Opened 2017-07-20 22:54 UTC by leem42

making prototypeVue branch up to date with master

2017-07-20 23:07 UTC, liujoshua requested changes

2017-07-20 23:07 UTC, liujoshua commented on .editorconfig
> +indent_size = 4
This contradicts js lint and the fact most files are indented by 2. We should either leave this at 2 or switch everything to 4.

2017-07-20 23:09 UTC, leem42 commented on .editorconfig
> +indent_size = 4
Ah, didn't read that correctly when I was merging, I can leave it at two

2017-07-20 23:10 UTC, liujoshua commented on src/components/Eligibility.vue
> +        <input v-focus="isUnderage" v-model="zipCode"  id="placeField" class="form-control inputLabel" type="number" pattern="\d*" placeholder="enter 5-digit zip"></input>
When place gets answered, doesn't this v-focus get called on this element again?

2017-07-20 23:15 UTC, leem42 commented on src/components/Eligibility.vue
> +        <input v-focus="isUnderage" v-model="zipCode"  id="placeField" class="form-control inputLabel" type="number" pattern="\d*" placeholder="enter 5-digit zip"></input>
Unless I'm misunderstanding something I don't believe so, on my local server I don't see the element highlight more than once

2017-07-20 23:40 UTC, liujoshua commented on src/components/Eligibility.vue
> +        <input v-focus="isUnderage" v-model="zipCode"  id="placeField" class="form-control inputLabel" type="number" pattern="\d*" placeholder="enter 5-digit zip"></input>
Add this inside focus function
`console.debug('focus directive: ' + el.outerHTML)`

2017-07-21 16:44 UTC, liujoshua approved these changes
Nice cleanup

2017-07-21 20:31 UTC, merged